### ISSUE TITLE
[TypeError: Object [object Object] has no method 'publishComposite']

### ISSUE THREAD

**Issue by kaamodt** [englue/meteor-publish-composite#19] opened 2014-11-09 23:19 UTC
Hi!

I have an application that, until now, has relied on reactivity on the client to update subscribtions that are dependent on other collections. This is working, but it seems as a rather hacky solution. After reading a bit on the reactive publications topic I came across this package and it seems very promising. 

Unfortunately, I am very quickly running into a problem. I have added the reywood:publish-composite package to my meteor application and added a call to Meteor.publishComposite() inside a file called publications.js under the server/ folder in my application. 

```
Meteor.publishComposite('allBids', function(game_id){
  return {
    find: function(){
      return Games.find({_id:game_id});
    },
    children: [
      {
        find: function(game){
          if (game.round_started){
            return Bids.find({'game_id':game._id, 'round':game.current_round});
          }
        }
      }
    ]
  }
});
```
Here I am trying to accomplish a reactive publish of the Bids collection when the field 'round_started' of a game is changed. I do not think this has any relevance to the issue, but just to be sure.

The console prints out this error:

```
publications.js" has syntax errors. [TypeError: Object [object Object] has no method 'publishComposite']
```
It seems the publishComposite function is not added to the Meteor namespace. Do I have to do anything special in order to set this up? I could not find anything in the README.

Am I doing something wrong here?

My meteor packages are:

```
accounts-password            1.0.4  Password support for accounts
email                        1.0.4  Send email messages
ian:accounts-ui-bootstrap-3  1.1.20  Bootstrap-styled accounts-ui with multi-language support.
ian:bootstrap-3              3.3.0_2  HTML, CSS, and JS framework for developing responsive, mobile first projects on the web.
iron:router                  1.0.1  Routing specifically designed for Meteor
reywood:publish-composite    1.3.3  Publish a set of related documents from multiple collections with a reactive join
sacha:spin                   2.0.4  Simple spinner package for Meteor
sanjo:jasmine                0.5.0  Easily use Jasmine in Meteor
standard-app-packages        1.0.3  Moved to meteor-platform
velocity:html-reporter       0.3.0-rc.3  Reactive Velocity test reports in your app.
```

Thanks, 

Kjetil

**Comment by ThePumpingLemma** [comment] 2015-03-13 01:35
The problem is with sanjo:jasmine. When it runs server side unit tests, it tries to call `publishComposite`. However, it doesn't exist in this case since sanjo:jasmine doesn't load the corresponding package in the server unit test context. You need to mock `publishComposite` in your unit tests to avoid this error.

**Comment by reywood** [comment] 2015-03-17 14:55
Thanks for shedding some light on this @ThePumpingLemma. Going to close this issue.

**Closed by reywood** 2015-03-17 14:55 UTC

**Comment by kaamodt** [comment] 2015-04-25 17:41
Thanks for the information @ThePumpingLemma  :)
