### ISSUE TITLE
Hard to trace bug

### ISSUE THREAD

**Issue by dburles** [englue/meteor-publish-composite#60] opened 2015-09-15 04:28 UTC
Just thought I'd post this one as it was a weird one to trace. I was bitten by a transform on a collection that placed a couple of default fields.

The problem was brought about by having two publications that would publish the same document. The first publication returned the document with the `fields` option. The second publication had no restriction.

The first publication would send across the document with the limited fields *plus* the default fields added by the transform. Where this really bit was when subscribing to pub 2 we would receive a `changed` message for the existing document but it wouldn't include the fields that were added through the transform function! The solution was to remove the transform from within the publication.

Cursors returned by publications by default don't apply the transformation function, is there a specific reason why publish-composite does?

**Comment by reywood** [comment] 2015-10-01 15:54
Sorry for the late reply. If you could put together a minimal meteor app that exhibits this behavior, it would be extremely helpful.

**Comment by reywood** [comment] 2015-10-01 16:20
Upon re-reading your comments, sounds like your issue is related to #28. The reason you don't see the transform when a document is changed is [explained here](https://github.com/englue/meteor-publish-composite/issues/28#issuecomment-130012786).

Going to close this as a duplicate of #28, but let me know if you feel this is a different issue.

**Closed by reywood** 2015-10-01 16:20 UTC

**Comment by dburles** [comment] 2015-10-02 00:27
Hey @reywood. My main question here is I am unsure why the transforms are being applied. Seems it would make sense to not apply any transformations in the context of the publications (as it is in a normal meteor publication).

**Comment by reywood** [comment] 2015-10-02 19:21
I explain why the transform is applied in [this comment](https://github.com/englue/meteor-publish-composite/issues/28#issuecomment-130012786) from #28.
